<html>
<head>
  <title>Физико-математический факультет ЕГУ им. И.А. Бунина ->> Гостевая книга</title>
  <meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
  <meta http-equiv="Content-Language" content="ru">
  <META content="Официальный сайт физико-математического факультета ЕГУ им. И.А. Бунина" name=Description>
  <META content="Елецкий Государственный Университет имени Ивана Алекеевича Бунина" name=Organisation>
  <META content="факультет университет высшее образование научная деятельность вуз школа студент абитуриент профессор доцент кандидат экзамен сессия зачет Елец Бунин ЕГУ аспирантура конференции наука" name=Keywords>
  <META content=alexander.shataloff@gmail.com name=OWNER>
  <META content="Шаталов Александр" name=Designer>
  <META content=index,follow name=ROBOTS>
  <META content="4 weeks" name=REVISIT-AFTER>
  <link href="http://fizmat.elsu.ru/images/logo.ico" rel="shortcut icon">
  <link href="http://fizmat.elsu.ru/styles/base.css" rel=stylesheet type=text/css>
  <script language=JavaScript src="http://fizmat.elsu.ru/scripts/others.js"></script>
</head>

<body ID=dbody NAME=dbody leftmargin="5" topmargin="5" marginwidth="5" marginheight="5" scroll=auto onload="Loading();">

<!--Таблица высотой 5 пикселей -->
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center" valign="middle" height="5"><A name=top></A></td>
  </tr>
</table>


<?php

 include("../index/flash.html");

?>

<!-- Основная таблица -->
<table width="770" border="0" cellspacing="2" bgcolor="#304078" cellpadding="0" align="center" valign="middle">
  <tr>
    <td colspan=3 bgcolor="#B4BEE4" height=20 valign="middle">
      <table width="766" border="0" cellspacing="2" cellpadding="0">
	<tr>
	  <td width="230" align="left">
            <font style="font-size:8pt;"><I>
              &nbsp;
              <script language=JavaScript>
                WriteDate()
              </script>
            </I></font>
          </td>

          <td width="*">
            <table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#304078">
              <tr>
                <td width="10" align="center" bgcolor="#91A3D9">&nbsp;</td>
                <td width="10" align="center" bgcolor="#5E78C6">&nbsp;</td>
                <td width="10" align="center" bgcolor="#3C57A8">&nbsp;</td>
                <td width="*" align="center">
                  <font class=zagolovok>··· ГОСТЕВАЯ КНИГА ···</font>
                </td>
                <td width="10" align="center" bgcolor="#3C57A8">&nbsp;</td>
                <td width="10" align="center" bgcolor="#5E78C6">&nbsp;</td>
                <td width="10" align="center" bgcolor="#91A3D9">&nbsp;</td>
              </tr>
            </table>
          </td>

          <td width="230" align="right">
            <font style="font-size:9pt;">
              <A class=menu href="javascript:history.back(1);" title="Назад">Назад</A>
              ·
              <A class=menu href="javascript:history.forward(1);" title="Вперед">Вперед</A>
              &nbsp;
            </font>
          </td>
        </tr>
      </table>
    </td>
  </tr>

  <tr>
    <td width="766" bgcolor="#DFE3F4" align="center" valign="middle" colspan=3>

    <table width="100%" height="100%" border="0" cellspacing="0" cellpadding="30"><tr><td align="center" valign="middle">

<!-- Здесь начинается содержание страницы ************************************************** -->

<?PHP

 // Удаление повторяющихся пробелов
 $name = chop($name);
 $lastname = chop($lastname);
 $email = chop($email);
 $msg = chop($msg);

 // Удаление пробелов в начале и в конце строки
 $name = trim($name);
 $lastname = trim($lastname);
 $email = trim($email);
 $msg = trim($msg);

 // Обрезание строк до определённой длины
 $name = substr($name,0,24);
 $lastname = substr($lastname,0,24);
 $email = substr($email,0,24);
 $msg = substr($msg,0,350);

 // Преобразование регистра
 $name = ucwords($name);          // Перевод во всех словах первых букв в заглавные
 $lastname = ucwords($lastname);  // Перевод во всех словах первых букв в заглавные
 $email = strtolower($email);     // Перевод в нижний регистр
 $msg = ucfirst($msg);            // Перевод первого символа в заглавный

 //Преобразование специальных символов в коды HTML
 $name = htmlspecialchars($name);
 $lastname = htmlspecialchars($lastname);
 $msg = htmlspecialchars($msg);

 $msg = str_replace(chr(13),"<br>",$msg);
 $msg = str_replace(chr(10),"",$msg);

 $error=0;
 $rec="";

 $times = Date("H:i");
 $dates = Date("d.m.Y");

 if (!preg_match("/^([a-z,0-9,_])+@([a-z,0-9])+(.([a-z,0-9])+)+$/", $email) && $email!="")
 {
   $error=1;
 }

 if ($error!=1 && $msg!="" && ($name!="" || $lastname!=""))
 {
   // Обработка пустых значений
   if ($name=="") { $name = "&nbsp;"; }

   if ($lastname=="") { $lastname = "&nbsp;"; }

   if ($email!="") { $email = "<a href=\"mailto:" . $email . "\">" . $email . "</a>"; }
   else { $email = "&nbsp;"; }

   $rec="\n<tr valign=\"middle\">" . "<td bgcolor=\"#CBD5ED\" rowspan=\"3\" align=\"center\">$times<br>$dates</td>";
   $rec=$rec . "<td bgcolor=\"#CBD5ED\" align=\"center\">$name</td>";
   $rec=$rec . "<td bgcolor=\"#CBD5ED\" rowspan=\"3\" style=\"text-align:justify;\"> &nbsp; &nbsp; $msg</td></tr>";
   $rec=$rec . "<tr valign=\"middle\"><td bgcolor=\"#CBD5ED\" align=\"center\">$lastname</td></tr>";
   $rec=$rec . "<tr valign=\"middle\"><td bgcolor=\"#CBD5ED\" align=\"center\">$email</td></tr>";

   // Запись данных в файл
   $file = "guests.txt";
   $open = fopen($file, "a+");
   fwrite($open, $rec);
   fclose($open);

   print ("<p style=\"font-size:12pt; text-align:center; line-height:18pt;\"><b>Ваши данные были успешно внесены в гостевую книгу</b></p>\n");

   print ("<hr width=\"100%\" align=\"center\" style=\"color: #304078;\" size=\"1\">");

   print ("<P align=center style=\"MARGIN-BOTTOM: 19px\"></P>\n");

   print ("<table width=\"100%\" border=\"0\" cellspacing=\"1\" cellpadding=\"2\" align=\"center\" bgcolor=\"#304078\">\n");
   print ("<tr valign=\"middle\" align=\"center\">\n");
   print ("<td width=\"18%\" bgcolor=\"#B4C5E4\">Дата и время внесения данных</td>\n");
   print ("<td width=\"30%\" bgcolor=\"#B4C5E4\">Имя, Фамилия, E-mail</td>\n");
   print ("<td width=\"52%\" bgcolor=\"#B4C5E4\">Сообщение</td>\n</tr>");

   print ("$rec");

   print ("</table>\n");

   print ("<P align=center style=\"MARGIN-BOTTOM: 19px\"></P>\n");

   print ("<hr width=\"100%\" align=\"center\" style=\"color: #304078;\" size=\"1\">");

   print ("<table height=22 width=140 border=\"1\" cellspacing=\"0\" cellpadding=\"0\" style=\"border-style: none;\">");
   print ("  <tr>");
   print ("   <td align=\"center\" width=140 onClick=\"top.location.href='http://fizmat.elsu.ru/gbook/archive.phtml';\"");
   print ("   class=t2 onmouseover=\"this.className='t1';\" onmouseout=\"this.className='t2';\">");
   print ("   Архив</td>");
   print ("  </tr>");
   print ("</table>");


 }
 else
 {
   if ($error!=0) { print ("<p style=\"font-size:12pt; text-align:center; line-height:18pt;\"><b>Не верно заполнено поле: E-mail!</b></p>"); }
   else { print ("<p style=\"font-size:12pt; text-align:center; line-height:18pt;\"><b>Некоторые из полей формы не заполнены!</b></p>"); }

   print ("<hr width=\"100%\" align=\"center\" style=\"color: #304078;\" size=\"1\">");

   print ("<P align=center style=\"MARGIN-BOTTOM: 19px\"></P>\n");

   print ("<table height=22 width=140 border=\"1\" cellspacing=\"0\" cellpadding=\"0\" style=\"border-style: none;\">");
   print ("  <tr>");
   print ("    <td align=\"center\" width=140 onClick=\"javascript:history.back(1);\"");
   print ("    class=t2 onmouseover=\"this.className='t1';\" onmouseout=\"this.className='t2';\">");
   print ("    Вернуться назад</td>");
   print ("  </tr>");
   print ("</table>");

 }

?>

<!-- Здесь заканчивается содержание страницы *********************************************** -->

      </td></tr></table>

    </td>
  </tr>

  <tr bgcolor="#B4BEE4">
    <td colspan=3 height=20 align="center" valign="middle">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr valign="middle">
          <td align="center" width="180"><a title="Сделать fizmat.elsu.ru стартовой страницей" class=menu href="" onClick="this.style.behavior='url(#default#homepage)';this.setHomePage('http://fizmat.elsu.ru/gbook/index.html'); return false;">
          Сделать страницу стартовой</a>
          </td>
          <td align="center" width="*">
          <a title="Перейти вверх страницы" class=menu href="#top">
          ··· Вверх ···</a>
          </td>
          <td align="center" width="180"><a title="Добавить сайт fizmat.elsu.ru в избранное: Ctrl+D" class=menu href="" onClick="window.external.addFavorite
          ('http://fizmat.elsu.ru/gbook/index.html', 'Физико-математический факультет ЕГУ им. И.А. Бунина - Гостевая книга'); return false;">
          Добавить сайт в избранное</a>
          </td>
        </tr>
      </table>
     </td>
  </tr>

  <tr bgcolor="#304078" height=20>
    <td colspan=3 align="center" valign="middle">
      <font style="font-size: 7pt;" color="#FFFFFF">
        <script language=JavaScript>
          WriteModified()
        </script>
        Оптимизировано для Internet Explorer 5.5 и Shockwave Flash 5. Рекомендуемое разрешение экрана 800x600.
        <a class=webmaster href="mailto:alexander.shataloff@gmail.com?subject=Письмо Web-мастеру fizmat.elsu.ru&Body=Уважаемый Web-мастер!" title="Напиши письмо Web-masterу">Web-master</a>
      </font>
    </td>
  </tr>

</table>

<!--Таблица высотой 5 пикселей -->
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center" valign="middle" height="5"> </td>
  </tr>
</table>

<?php include("../index/counters.html"); ?>

</body>
</html>