<?php

if(!isset($flash)) $flash="no";
if ($flash!='no') { $flash='yes'; }
// $flash='yes';

?>

<html>

<head>
<title>Физико-математический факультет ЕГУ им. И.А. Бунина ->> Главная</title>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
<meta http-equiv="Content-Language" content="ru">
<META content="Официальный сайт физико-математического факультета ЕГУ им. И.А. Бунина" name=Description>
<META content="Елецкий Государственный Университет имени Ивана Алекеевича Бунина" name=Organisation>
<META content="физико-математический факультет физмат университет высшее образование научная деятельность вуз школа студент абитуриент профессор доцент кандидат экзамен сессия зачет Елец Бунин ЕГУ аспирантура конференции наука" name=Keywords>
<META content=alexander.shataloff@gmail.com name=OWNER>
<META content="Шаталов Александр" name=Designer>
<META content=index,follow name=ROBOTS>
<META NAME="Document-state" CONTENT="Dynamic">
<META NAME="Revizit-after" CONTENT="10 days">
<META NAME="ask" CONTENT="Дорогие Пауки и Модераторы каталогов! Присылайте сюда побольше посетителей, пожалуйста!">
<link href="http://fizmat.elsu.ru/images/logo.ico" rel="shortcut icon">
<link href="http://fizmat.elsu.ru/styles/base.css" rel=stylesheet type=text/css>
<script language=JavaScript src="http://fizmat.elsu.ru/scripts/others.js"></script>
</head>

<body leftmargin="5" topmargin="5" marginwidth="5" marginheight="5" scroll=auto

<?php
 if ($flash=='yes') { print (" ID=dbody NAME=dbody onload=\"Loading();\"> "); }
 if ($flash=='no') { print (" background=\"http://fizmat.elsu.ru/images/fon.gif\"> "); }
?>

<!-- Таблица высотой 5 пикселей -->
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td align="center" valign="middle" height="5"><A name=top></A></td>
</tr>
</table>

<?php
 if ($flash=='yes') { include("index/flash.html"); }
 if ($flash=='no') { include("index/noflash.html"); }
?>

<!-- Основная таблица -->
<table width="770" border="0" cellspacing="2" bgcolor="#304078" cellpadding="0" align="center" valign="middle">
<tr>
<td colspan=3 bgcolor="#B4BEE4" height=20 valign="middle">
<table width="766" border="0" cellspacing="2" cellpadding="0">
<tr>
<td width="230" align="left">
<font style="font-size:8pt;"><I>
&nbsp;
<script language=JavaScript>
WriteDate()
</script>
</I></font>
</td>
<td width="*">
<table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#304078">
<tr>
<td width="10" align="center" bgcolor="#91A3D9">&nbsp;</td>
<td width="10" align="center" bgcolor="#5E78C6">&nbsp;</td>
<td width="10" align="center" bgcolor="#3C57A8">&nbsp;</td>
<td width="*" align="center">
<font class=zagolovok>··· ГЛАВНАЯ ···</font>
</td>
<td width="10" align="center" bgcolor="#3C57A8">&nbsp;</td>
<td width="10" align="center" bgcolor="#5E78C6">&nbsp;</td>
<td width="10" align="center" bgcolor="#91A3D9">&nbsp;</td>
</tr>
</table>
</td>
<td width="230" align="right">
<font style="font-size:9pt;">
<A class=menu href="javascript:history.back(1);" title="Назад">Назад</A>
·
<A class=menu href="javascript:history.forward(1);" title="Вперед">Вперед</A>
&nbsp;
</font>
</td>
</tr>
</table>
</td>
</tr>
<tr>

<!-- Здесь начинается левая часть *************************************** -->

<td bgcolor="#CBD5ED" valign="top" align="center" width=180>
<table width=180 border="0" cellspacing="0" cellpadding="0" style="margin-top: 10; margin-bottom: 10;">
<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 align="left"><b>Поиск</b>
</td>
<td width=10></td>
</tr>
<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 align="center">
<FORM method="GET" action="http://www.google.com/custom" NAME="finder">
<table height=22 width=160 border="0" cellspacing="0" cellpadding="0" style="border-style: none;">
<tr>
<td align="center" width=123>
<INPUT class=bar TYPE=text name=q size=20 maxlength=255 value="Что ищем?"
onblur="if (this.value=='') {this.value=this.defaultValue;}"
onfocus="if (this.value==this.defaultValue) {this.value='';}"
style="width: 123px; height: 22px;">
<INPUT type=hidden name=cof VALUE="T:#336699;AH:center;GL:0;S:http://www.elsu.ru;AWFID:5d3934e7ecc4c415;">
<input type=hidden name=domains value="elsu.ru">
</td>
<td width=32 onClick="document.finder.submit();"
class=t2 onmouseover="this.className='t1';" onmouseout="this.className='t2';">
Go
</td>
</tr>
<tr>
<td align="center" colspan=2>
<input type=radio name=sitesearch value="elsu.ru" checked> сайт &nbsp;
<input type=radio name=sitesearch value=""> интернет
</td>
</tr>
</table>
</FORM>
<P align=center style="MARGIN-BOTTOM: -18px"></P>
</td>
<td width=10></td>
</tr>
<tr bgcolor="#CBD5ED" align="center" height="10" valign="middle">
<td width=10></td>
<td colspan="3" height="10">
<hr width="100%" align="center" style="color: #304078;" size="1">
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 align="left"><b>Ссылки <a class=news href="http://www.elsu.ru/" style="font-size: 10pt;" title="Официальный сайт ЕГУ им. И.А. Бунина">ELSU.RU</a></b></td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td width=10></td>
<td align="center">
<table width=140 border="1" cellspacing="2" cellpadding="0" style="border-style: none;">
<tr height=22>
<td align="center" width=140 onClick="top.location.href='http://www.elsu.ru/news';"
class=t2 onmouseover="this.className='t1';" onmouseout="this.className='t2';">
Новости</td>
</tr>
<tr height=22>
<td align="center" width=140 onClick="top.location.href='http://www.elsu.ru/facultet';"
class=t2 onmouseover="this.className='t1';" onmouseout="this.className='t2';">
Факультеты</td>
</tr>
<tr height=22>
<td align="center" width=140 onClick="top.location.href='http://www.elsu.ru/kafedra';"
class=t2 onmouseover="this.className='t1';" onmouseout="this.className='t2';">
Кафедры</td>
</tr>
<tr height=22>
<td align="center" width=140 onClick="top.location.href='http://people.elsu.ru/';"
class=t2 onmouseover="this.className='t1';" onmouseout="this.className='t2';">
«Люди ЕГУ»</td>
</tr>
</table>
<P align=center style="MARGIN-BOTTOM: -18px"></P>
</td>
<td width=10></td>
<td width=10></td>
</tr>
<tr bgcolor="#CBD5ED" align="center" height="10" valign="middle">
<td width=10></td>
<td colspan="3" height="10">
<hr width="100%" align="center" style="color: #304078;" size="1">
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 align="left"><b>Голосование</b></td>
<td width=10></td>
</tr>
<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 align="center"><i>Где Вы собираетесь провести лето?</i></td>
<td width=10></td>
</tr>
<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 align="center">
<form action="http://fizmat.elsu.ru/polls/index.phtml" method="post" name="polls">
<table border="0" cellspacing="0" cellpadding="0" style="border-style: none;">
<tr><td><input name="v1" type="radio" value="0"><i>На курорте</i></td><tr>
<tr><td><input name="v1" type="radio" value="1"><i>Поеду работать в лагерь</i></td><tr>
<tr><td><input name="v1" type="radio" value="2"><i>Останусь в родном городе</i></td><tr>
<tr><td><input name="v1" type="radio" value="3" checked><i>У родственников (в деревне, на даче и т.п.)</i></td><tr>
</table>
<table height=22 width="140" border="0" cellspacing="0" cellpadding="0" style="border-style: none;">
<tr>
<td width="100%" onClick="document.polls.submit();"
class=t2 onmouseover="this.className='t1';" onmouseout="this.className='t2';">
Голосовать
</td>
</tr>
</table>
<A class=menu href="http://fizmat.elsu.ru/polls/" title="Результаты голосования">··· Результаты ···</A>
</form>
<P align=center style="MARGIN-BOTTOM: -19px"></P>
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED" align="center" height="10" valign="middle">
<td width=10></td>
<td colspan="3" height="10">
<hr width="100%" align="center" style="color: #304078;" size="1">
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 align="left"><b>Пейджеры</b></td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 align="center">

<FORM name=pager action="http://leschat.lipetsk.ru/html/pgate.php" method=post>
<CENTER>

<SELECT class=bar name=company style="width: 140; margin-top: 4px;">
<OPTION value=Липецк-Пэйджинг selected>Липецк-Пэйджинг</OPTION>
<OPTION value=Экском-Липецк>Экском-Липецк</OPTION>
<OPTION value="Мобил Телеком">Мобил Телеком</OPTION>
<OPTION value=Континенталь>Континенталь</OPTION>
</SELECT>

<INPUT class=bar style="width: 140; margin-top: 1px;"
      onblur="if (this.value=='') {this.value=this.defaultValue;}"
      onfocus="if (this.value==this.defaultValue) {this.value='';}" maxLength=6
      size=18 value=номер name=pager_no>

<BR><INPUT class=bar style="width: 140; margin-top: 1px; margin-bottom: 1px;"
      onblur="if (this.value=='') {this.value=this.defaultValue;}"
      onfocus="if (this.value==this.defaultValue) {this.value='';}"
      maxLength=120 size=18 value=сообщение name=pager_message>

<table height=22 width="140" border="0" cellspacing="0" cellpadding="0" style="border-style: none;">
<tr>
<td width="100%" onClick="document.pager.submit();"
class=t2 onmouseover="this.className='t1';" onmouseout="this.className='t2';">
Отправить
</td>
</tr>
</table>

</CENTER>
</FORM>

<P align=center style="MARGIN-BOTTOM: -16px"></P>
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED" align="center" height="10" valign="middle">
  <td width=10></td>
  <td colspan="3" height="10">
    <hr width="100%" align="center" style="color: #304078;" size="1">
  </td>
  <td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
  <td width=10></td>
    <td colspan=3 align="left"><b>Download</b></td>
  <td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
  <td width=10></td>
  <td colspan=3 style="text-align:left; font-size:8pt; ">
    <b class=newsdate>1</b> - Е.С. Фёдоров, О.В. Ерёмин "Шпаргалка вожатого" (игры, тесты, методики) - Word&nbsp;2000 - 47k
    <DIV ALIGN=RIGHT><A class=news HREF="useful/shpora.zip" title="Скачать файл">скачать...</A></DIV>
  </td>
  <td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
  <td width=10></td>
  <td colspan=3 style="text-align:left; font-size:8pt; ">
    <b class=newsdate>2</b> - "Положение о ВКР"&nbsp;(2002г.) - Word&nbsp;2000 - 26k
    <DIV ALIGN=RIGHT><A class=news HREF="useful/vkr2002.zip" title="Скачать файл">скачать...</A></DIV>
  </td>
  <td width=10></td>
</tr>


<tr bgcolor="#CBD5ED" align="center" height="10" valign="middle">
<td width=10></td>
<td colspan="3" height="10">
<hr width="100%" align="center" style="color: #304078;" size="1">
</td>
<td width=10></td>
</tr>


<tr bgcolor="#CBD5ED">
  <td width=10></td>
  <td colspan=3 align="center">

<form name=form_var3b method=POST action='http://www.translate.ru/rus/url/tran_url.php'><table width=160 border=0 cellspacing=0 cellpadding=0>
<script language='JavaScript'>
<!-- Begin
var var3b_up = new Image();
var3b_up.src = 'http://www.translate.ru/images/forms/var3b_up.gif';
var var3b_down = new Image();
var3b_down.src = 'http://www.translate.ru/images/forms/var3b_down.gif';
function movepic_new (img_obj, img_src)
{
img_obj.src = img_src.src;
return true;
}
// -->
</script>
<tr><td colspan=2 height=19 background='http://www.translate.ru/images/forms/var3b_1.gif'><img src='http://www.translate.ru/images/forms/var3b_1.gif' border=0 width=160 height=19></td></tr>
<tr><td width=105 height=31 align=center background='http://www.translate.ru/images/forms/var3b_2.gif' style='font-family: Verdana; font-size: 12px'><select name=direction size=1 style='font-family: Verdana; font-size: 12px'>
<option value='re'>English</option><option value='rg'>German</option><option value='rf'>French</option></select></td>
<td width=55 height=31 align=center valign=top background='http://www.translate.ru/images/forms/var3b_3.gif'><input type=image vspace=2 name=btn_var3b alt='Translate!' width=35 height=25 border=0 src='http://www.translate.ru/images/forms/var3b_up.gif' onmousedown='javascript:movepic_new(this, var3b_down);' onmouseup='javascript:movepic_new(this, var3b_up);' onmouseout='javascript:movepic_new(this, var3b_up);'></td></tr>
<input type=hidden name=template value='General'>
<script language='JavaScript'>
<!-- Begin
document.write('<input type=hidden name=url value="');
document.write(window.location.href);
document.write('">');
//   End -->
</script>
</table>
</form>

  </td>
  <td width=10></td>
</tr>


<tr bgcolor="#CBD5ED" align="center" height="10" valign="middle">
<td width=10></td>
<td colspan="3" height="10">
<hr width="100%" align="center" style="color: #304078;" size="1">
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED" align="center" valign="middle">
<td width=10></td>
<td colspan="3" height="10">
<a href="http://www2.gismeteo.ru/weather/towns/27928.htm">
<img lowsrc="http://fizmat.elsu.ru/images/one.gif" alt="ФОБОС: погода в г.Елец" src="http://informer.gismeteo.ru/27928-10.GIF" border=0 width=120 height=60 style="margin-top: 3px;"></a>
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED" align="center" height="10" valign="middle">
<td width=10></td>
<td colspan="3" height="10">
<hr width="100%" align="center" style="color: #304078;" size="1">
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED" align="center" valign="middle">
<td width=10></td>
<td colspan="3" height="10">
<a href="http://www.yelets.ru/chat/index.php" target="_blank"><img alt="Елецкий чат" lowsrc="http://fizmat.elsu.ru/images/one.gif" src="http://fizmat.elsu.ru/images/echat.gif" width="88" height="31" border="0" style="margin-top: 3px;"></a>
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED" align="center" valign="middle">
<td width=10></td>
<td colspan="3" height="10">
<a href="http://www.elets.elsu.ru/" target="_blank"><img alt="Елец и ельчане" lowsrc="http://fizmat.elsu.ru/images/one.gif" src="http://fizmat.elsu.ru/images/elets.gif" width="88" height="31" border="0" style="margin-top: 3px;"></a>
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED" align="center" height="10" valign="middle">
<td width=10></td>
<td colspan="3" height="10">
<hr width="100%" align="center" style="color: #304078;" size="1">
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED" align="center" valign="middle">
  <td width=10></td>
  <td colspan="3" height="10">

<!--Rating@Mail.ru COUNTER--><script language="JavaScript"><!--
d=document;a='';a+=';r='+escape(d.referrer)
js=10//--></script><script language="JavaScript1.1"><!--
a+=';j='+navigator.javaEnabled()
js=11//--></script><script language="JavaScript1.2"><!--
s=screen;a+=';s='+s.width+'*'+s.height
a+=';d='+(s.colorDepth?s.colorDepth:s.pixelDepth)
js=12//--></script><script language="JavaScript1.3"><!--
js=13//--></script><script language="JavaScript"><!--
d.write('<a href="http://top.mail.ru/jump?from=489231"'+
' target=_top><img src="http://top.list.ru/counter'+
'?id=489231;t=211;js='+js+a+';rand='+Math.random()+
'" alt="Рейтинг@Mail.ru"'+' border=0 height=31 width=88></a>')
if(js>11)d.write('<'+'!-- ')//--></script><noscript><a
target=_top href="http://top.mail.ru/jump?from=489231"><img
src="http://top.list.ru/counter?js=na;id=489231;t=211"
border=0 height=31 width=88
alt="Рейтинг@Mail.ru"></a></noscript><script language="JavaScript"><!--
if(js>11)d.write('--'+'>')//--></script><!--/COUNTER-->

  </td>
  <td width=10></td>
</tr>

<tr bgcolor="#CBD5ED" align="center" valign="middle">
  <td width=10></td>
  <td colspan="3" height="10">

<!-- HotLog -->
<script language="javascript">
hotlog_js="1.0";
hotlog_r=""+Math.random()+"&s=90380&im=101&r="+escape(document.referrer)+"&pg="+
escape(window.location.href);
document.cookie="hotlog=1; path=/"; hotlog_r+="&c="+(document.cookie?"Y":"N");
</script><script language="javascript1.1">
hotlog_js="1.1";hotlog_r+="&j="+(navigator.javaEnabled()?"Y":"N")</script>
<script language="javascript1.2">
hotlog_js="1.2";
hotlog_r+="&wh="+screen.width+'x'+screen.height+"&px="+
(((navigator.appName.substring(0,3)=="Mic"))?
screen.colorDepth:screen.pixelDepth)</script>
<script language="javascript1.3">hotlog_js="1.3"</script>
<script language="javascript">hotlog_r+="&js="+hotlog_js;
document.write("<a href='http://click.hotlog.ru/?90380' target='_top'><img "+
" src='http://hit5.hotlog.ru/cgi-bin/hotlog/count?"+
hotlog_r+"&' border=0 width=88 height=31 alt=HotLog></a>")</script>
<noscript><a href=http://click.hotlog.ru/?90380 target=_top><img
src="http://hit5.hotlog.ru/cgi-bin/hotlog/count?s=90380&im=101" border=0
width="88" height="31" alt="HotLog"></a></noscript>
<!-- /HotLog -->

  </td>
  <td width=10></td>
</tr>

<tr bgcolor="#CBD5ED" align="center" height="2" valign="middle">
  <td colspan=5></td>
</tr>

<tr bgcolor="#CBD5ED" align="center" valign="middle">
  <td width=10></td>
  <td colspan="3" height="10">

     <!--begin of Top100 logo-->
     <a href="http://top100.rambler.ru/top100/">
     <img src="http://top100-images.rambler.ru/top100/banner-88x31-rambler-darkblue2.gif" alt="Rambler's Top100" width=88 height=31 border=0></a>
     <!--end of Top100 logo -->

  </td>
  <td width=10></td>
</tr>

<tr bgcolor="#CBD5ED" align="center" height="2" valign="middle">
  <td colspan=5></td>
</tr>

</table>
</td>
<!-- Конец - Левая часть **************************************** -->

<!-- Начало - Средняя часть ************************************* -->
<td width="402" bgcolor="#DFE3F4" align="center" valign="top">

<table cellspacing="0" cellpadding="10">

<?php

  if ($flash=='no') {

  print (" <tr><td><TABLE width=\"100%\" cellSpacing=\"0\" cellPadding=\"0\" align=\"center\" border=\"0\"><TR> ");
  print (" <TD align=\"center\" valign=\"middle\" style=\"font-size:8pt;\"> ");
  print (" <b>ВНИМАНИЕ!</b> Навигационное меню нашего сайта использует технологию Macromedia Shockwave Flash. ");
  print (" Если у Вас возникнут проблемы, советуем воспользоваться ");
  print (" <A class=news HREF=\"http://fizmat.elsu.ru/map/\" title=\"Карта сайта\">картой сайта</A> или установить ");
  print (" <A class=news HREF=\"http://fizmat.elsu.ru/download/\" title=\"Flash Player\">Flash Player</A> ");
  print (" </TD></TR></TABLE>&nbsp;<hr width=\"100%\" align=\"center\" style=\"color: #304078;\" size=\"1\"></td></tr> ");

                    }


  if ($flash=='yes') {

  print (" <tr><td align=\"center\"> ");

  print (" <table width=\"380\" height=\"60\" cellspacing=\"0\" cellpadding=\"0\" style=\"border: 1px solid black;\"> ");

  print (" <tr><td background=\"http://fizmat.elsu.ru/images/fonbanner.gif\"> ");

  print (" <OBJECT classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" id=\"cong_flash4\" width=\"380\" height=\"60\"> ");
  print (" <PARAM NAME=movie VALUE=\"http://fizmat.elsu.ru/images/cong_flash4.swf\"> ");
  print (" <PARAM NAME=wmode VALUE=transparent> ");
  print (" <PARAM NAME=quality VALUE=high> ");
  print (" <PARAM NAME=menu VALUE=false> ");
  print (" <PARAM NAME=devicefont VALUE=true> ");
  print (" <EMBED src=\"http://fizmat.elsu.ru/images/cong_flash4.swf\" wmode=\"transparent\" menu=\"false\" devicefont=\"true\" quality=\"high\" NAME=\"cong_flash4\" width=\"380\" height=\"60\" TYPE=\"application/x-shockwave-flash\"> ");
  print (" </EMBED></OBJECT> ");

  print (" </td></tr></table></td></tr> ");

                     }

?>

<tr><td>
<TABLE width="100%" cellSpacing="0" cellPadding="0" align="center" border=0" style="margin-top: -10;">
<TR>
<TD align="left" valign="middle">
<IMG LOWSRC="http://fizmat.elsu.ru/images/one.gif" SRC="http://fizmat.elsu.ru/images/dean.jpg" align="left" border="0" title="М.А. Аверьянова" width="111" height="185">
</TD>
<TD style="font-size:10pt; color: #000034;" align="center">
<I>Добро пожаловать на сайт<br>физико–математического факультета<br>Елецкого государственного университета имени И.А. Бунина,<br>славящегося традициями в научной и общественной жизни ВУЗа, города, области, большим творческим потенциалом преподавателей<br>и студентов</I>
<div style="margin-top: 6px;" style="font-size:10pt;" ><b>Декан &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; М.А. Аверьянова</b></div>
</TD>
</TR>
</TABLE>
</td></tr>
<tr><td>
<TABLE width="100%" cellSpacing="1" cellPadding="2" align="center" border=0 bgcolor="#304078" style="margin-top: -10;">
<TBODY align="center">
<TR bgcolor="#B4C5E4">
<TD style="font-size:12pt;" colspan=2><B>С Днём Рождения!</B></TD>
</TR>

<?php require ("birthday/script.php"); ?>

</TBODY>
</TABLE>
</td></tr>

<!--
<tr><td>
<table bgcolor="#304078" width="100%" cellSpacing="1" cellPadding="5" align="center" border="0" style="margin-top: -10;">
  <tr bgcolor="#B4C5E4">
    <td>
      <CENTER><B>СЛОВО ОТ WEB-МАСТЕРА</B></CENTER>
    </td>
  </tr>
  <tr bgcolor="#CBD5ED">
    <td>
      <P style="margin-top: 4px; text-align: justify;">


<IMG LOWSRC="http://fizmat.elsu.ru/images/one.gif"
SRC="http://fizmat.elsu.ru/images/webmaster.jpg" align="left" width="120"
vspace="8" height="167" style="border: solid black 1px; margin-right: 10px;"
title="Web-мастер">


        Вот и закончилось моё обучение в университете, а следовательно и
        дальнейшая работа над этим сайтом. Вы спросите: "Легко ли было?" Отвечу:
        "Нет, не легко!" Не смотря на то, что HTML уже изучается в школах,
        трудностей и различного рода "подводных камней" было хоть отбавляй. Тем
        более, что мы стали первым факультетом у которого появился свой сайт.
        Информацию добывал с миру по нитке, в основном это конечно статьи из
        газет и книг. Обидно и то, что на призыв о наполнении сайта откликнулись
        очень не многие. Поэтому практически всю работу приходилось выполнять в
        одиночку. Одним словом, данная область у нас ещё не так сильно развита
        как этого бы хотелось. Не стоит и удивляться, что факультетский сайт
        существует всего в одном экземпляре. Одно время были планы
        сделать совместный проект с экономическим факультетом, видя их рвение и
        горящие глаза. Но в виду некоторых обстоятельств и нехватки времени, эту
        идею пришлось отложить.

      </P>
      <P style="margin-top: -18px; text-align: justify; text-indent:18pt;">

        Говорить о том, удался ли проект или нет, Я не буду. Вам решать. Но
        всё зависящее от себя Я сделал.

      </P>
      <P style="margin-top: -18px; text-align: justify; text-indent:18pt;">

        Хочу выразить слова огромной благодарности следующим
        замечательным людям помогавшие в осуществлении данного проекта:
        М.А.&nbsp;Аверьяновой, Н.В.&nbsp;Черноусовой, С.Н.&nbsp;Дворяткиной,
        С.В.&nbsp;Бровко, О.Н.&nbsp;Гнездиловой, А.Б.&nbsp;Трегубову,
        К.О.&nbsp;Сладкову, Е.Ю.&nbsp;Красеву, Р.С.&nbsp;Сапрыкину,
        Т.А.&nbsp;Курбатовой и другим.

      </P>
      <P style="margin-top: -18px; text-align: justify; text-indent:18pt;">

        C 9-го июля поддержкой и наполнением сайта будет заниматься Захаров
        Андрей. Прошу любить и жаловать!

      </P>
      <P style="margin-top: -18px; text-align: justify; text-indent:18pt;">

        Если у Вас для меня есть интересные идеи и предложения, с удовольствием их
        рассмотрю. Присылайте их на <a href="mailto:alexander.shataloff@gmail.com">e-mail</a>.
      </P>
    </td>
  </tr>
</table>
</td></tr>

-->

<tr><td>
<table bgcolor="#304078" width="100%" cellSpacing="1" cellPadding="5" align="center" border="0" style="margin-top: -10;">
  <tr bgcolor="#B4C5E4">
    <td>
      <CENTER><B>ПОЗДРАВЛЯЕМ!</B></CENTER>
    </td>
  </tr>
  <tr bgcolor="#CBD5ED">
    <td>
      <P style="margin-top: 4px; text-align: justify;">
        Доцента кафедры математического анализа и элементарной математики
        <a href="http://people.elsu.ru/savvina/">Ольгу&nbsp;&nbsp;Алексеевну&nbsp;&nbsp;Саввину</a>
        с блестящей защитой в Московском государственном
        областном университете сразу по двум специальностям: "Общая педагогика.
        История педагогики и образования" и "Теория и методика обучения и
        воспитания ("Математика")".
      </P>
    </td>
  </tr>
</table>
</td></tr>


<tr><td>
<table bgcolor="#304078" width="100%" cellSpacing="1" cellPadding="5" align="center" border="0" style="margin-top: -10;">

<tr bgcolor="#B4C5E4"><td>
<CENTER><B>СТУДЕНТ, УЧИСЬ УЧИТСЯ!</B></CENTER>
</td></tr>

<tr bgcolor="#CBD5ED"><td>

<P style="margin-top: 4px; text-align: justify;">

<a href="http://fizmat.elsu.ru/photo/real.phtml?number=60" target="_blank">
<IMG LOWSRC="http://fizmat.elsu.ru/images/one.gif" SRC="http://fizmat.elsu.ru/photo/small/061.jpg" align="left" width="120"
vspace="2" height="83" style="border: solid black 1px; margin-right: 10px;"
title="Студенты группы М-24 обсуждают план воспитательной работы с завучем средней школы №95 И.В.Дурневой"></a>

У    студентов   первых   курсов  началось  знакомство с профессией педагога в
рамках   непрерывной   педагогической   практики   (НПП)  -  первой  из  шести
запланированных на весь период обучения.

<BR>Во     втором     семестре     студенты    знакомятся    c    организацией
учебно-воспитательного   процесса    школы    и   учреждений   дополнительного
образования   нашего  города:  Дом  школьника,   центры  социального  здоровья
подростков   и   молодёжи,  станции юных техников, станции юных туристов, клуб
старшеклассников, школа искусств.

<a href="http://fizmat.elsu.ru/photo/real.phtml?number=61" target="_blank">
<IMG LOWSRC="http://fizmat.elsu.ru/images/one.gif" SRC="http://fizmat.elsu.ru/photo/small/062.jpg" align="left" width="120"
vspace="4" height="79" style="border: solid black 1px; margin-right: 10px;"
title="Учащиеся 6-го класса рады встрече со студенткой II&nbsp;курса Скиба Мариной"></a>

<BR>Второкурсники  весь  четвёртый  семестр  стажируются в классах   городских
школ,    где    проходят    свою   НПП.   Продолжают  изучать профессиональную
деятельность,  накапливают  первоначальный  педагогический  опыт, знакомятся с
основами работы учителя, классного руководителя.

<BR>На  следующий  год  повзрослевших  студентов  ждёт  летняя  педагогическая
практика, которая проходит в оздоровительных лагерях.

<BR>В  восьмом  и девятом семестре студенты на целых два месяца покидают ВУЗ и
идут  в  школы,  лицеи,  гимназии,  чтобы  попробывать  себя  в роли учителя и
классного  руководителя.  Лучшие студенты работают по месту жительства. За это
время каждый накапливает материал для курсовых и квалификационных работ.

</P>

</td></tr>
</table>
</td></tr>

<tr><td>
<table bgcolor="#304078" width="100%" cellSpacing="1" cellPadding="5" align="center" border="0" style="margin-top: -10;">

<tr bgcolor="#B4C5E4"><td>
<CENTER><B>ФИЛОСОФИЯ ЧУДА ИЛИ ДИВО НОВОГО ВЕКА</B></CENTER>
</td></tr>

<tr bgcolor="#CBD5ED"><td>

<P style="margin-top: 4px; text-align: justify;">
<a href="http://vitas.com.ru" target="_blank"><IMG LOWSRC="http://fizmat.elsu.ru/images/one.gif" SRC="http://fizmat.elsu.ru/images/vitas.jpg" align="left" width="120" vspace="2" height="83" style="border: solid black 1px; margin-right: 10px;" title="Витас"></a>

На 4-ом курсе физико-математического факультета состоялся открытый кураторский час, который подготовила и провела доцент кафедры математического анализа и элементарной математики
<a href="http://people.elsu.ru/dvoryatkina/">Дворяткина Светлана Николаевна</a>. Тема занятия -
<a href="http://fizmat.elsu.ru/rest/hour/">"Философия чуда или диво нового века"</a>.
</P>

</td></tr>
</table>
</td></tr>

</table>
</td>
<!-- Здесь заканчивается средняя часть ***************************************************** -->

<!-- Здесь начинается правая часть ********************************************************* -->
<td width="180" bgcolor="#CBD5ED" align="center" width="180" valign="top">
<table width="180" border="0" cellspacing="0" cellpadding="0" style="margin-top: 10; margin-bottom: 10;">
<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 align="left"><b>Новости</b></td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 style="text-align:left; font-size:8pt; ">
<b class=newsdate>17.05.2003</b> - Команда КВН физико-математического факультета заняла <b>I место</b> в первом областном фестивале студенческих команд КВН
<DIV ALIGN=RIGHT>&nbsp;</DIV>
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 style="text-align:left; font-size:8pt; ">
<b class=newsdate>16.05.2003</b> - Прозвенел последний звонок для выпускного курса
<DIV ALIGN=RIGHT>&nbsp;</DIV>
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 style="text-align:left; font-size:8pt; ">
<b class=newsdate>14.05.2003</b> - День здоровья
<DIV ALIGN=RIGHT>&nbsp;</DIV>
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 style="text-align:left; font-size:8pt; ">
<b class=newsdate>07.05.2003</b> - День физмата
<DIV ALIGN=RIGHT>&nbsp;</DIV>
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 style="text-align:left; font-size:8pt; ">
<b class=newsdate>09.04.2003</b> - Прошла научно-практическая конференция преподавателей физ.-мат. факультета
<DIV ALIGN=RIGHT><A class=news HREF="news/index.html#n9" title="Читайте подробности">подробнее...</A></DIV>
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 style="text-align:left; font-size:8pt; ">
<b class=newsdate>08.04.2003</b> - Прошла научно-практическая конференция студентов физ.-мат. факультета
<DIV ALIGN=RIGHT><A class=news HREF="news/index.html#n8" title="Читайте подробности">подробнее...</A></DIV>
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 style="text-align:left; font-size:8pt; ">
<b class=newsdate>03.04. - 04.04.</b> - Состоялся научно-методический семинар "Информатика: концепции, современное состояние, перспективы развития"
<DIV ALIGN=RIGHT><A class=news HREF="news/index.html#n7" title="Читайте подробности">подробнее...</A></DIV>
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td width=10></td>
<td align="center">
<A class=menu HREF="news/index.html" title="Архив новостей">··· Архив ···</A>
</td>
<td width=10></td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED" align="center" height="10" valign="middle">
<td width=10></td>
<td colspan="3" height="10">
<hr width="100%" align="center" style="color: #304078;" size="1">
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 align="left"><b>Новости сайта</b></td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 style="text-align:left; font-size:8pt; ">
<b class=newsdate>06.07.2003</b> - Установлена форма для перевода страниц сайта с русского на английский, немецкий и французский языки
<DIV ALIGN=RIGHT>&nbsp;</DIV>
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 style="text-align:left; font-size:8pt; ">
<b class=newsdate>05.07.2003</b> - Прошло уже четыре месяца со дня опубликования сайта в сети Internet.
<br><br><center><i>
Создателям сайта очень важно Ваше мнение об этом проекте.
<br>Оставьте в <a class=menu href="http://fizmat.elsu.ru/gbook/">гостевой книге</a> свои пожелания, отзывы и предложения
</i></center>
<DIV ALIGN=RIGHT>&nbsp;</DIV>
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 style="text-align:left; font-size:8pt; ">
<b class=newsdate>29.05.2003</b> - Открыт раздел
<a class=menu href="http://fizmat.elsu.ru/reading/">"Читай то, что интересно"</a>
<DIV ALIGN=RIGHT>&nbsp;</DIV>
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 style="text-align:left; font-size:8pt; ">
<b class=newsdate>28.05.2003</b> - Обновлён дизайн сайта
<DIV ALIGN=RIGHT>&nbsp;</DIV>
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED" align="center" height="10" valign="middle">
<td width=10></td>
<td colspan="3" height="10">
<hr width="100%" align="center" style="color: #304078;" size="1">
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 align="left"><b>Объявления</b></td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 style="text-align:left; font-size:8pt; ">
<b class=newsdate>04.07.2003</b> - Ректорат и оргкомитет приглашают выпускников физмата 1963-го года на юбилейную встречу, которая состоится 04.07.03 в 11:00 утра по адресу:
<a class=menu href="http://fizmat.elsu.ru/photo/real.phtml?number=0" target="_blank">ул.&nbsp;Ленина, д.91</a>
<DIV ALIGN=RIGHT>&nbsp;</DIV>
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td width=10></td>
<td align="center">
<A class=menu HREF="board/index.html" title="Архив объявлений">··· Архив ···</A>
</td>
<td width=10></td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED" align="center" height="10" valign="middle">
<td width=10></td>
<td colspan="3" height="10">
<hr width="100%" align="center" style="color: #304078;" size="1">
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 align="left"><b>Читай то, что интересно</b></td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 style="text-align:left; font-size:8pt; ">
<b class=newsdate>По следам слухов</b> - Служить бы рад, да школа не пускает.
<br><i>Говорят о том, что подготовлен указ президента, освободжающий от службы в армии молодых педагогов...</i>
<DIV ALIGN=RIGHT><A class=news HREF="reading/index.phtml?number=7" title="Читайте подробности">подробнее...</A></DIV>
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 style="text-align:left; font-size:8pt; ">
<b class=newsdate>Житье-бытье</b> - Наука выживания.
<br><i>Студенчество - самый бурный период всей нашей жизни...</i>
<DIV ALIGN=RIGHT><A class=news HREF="reading/index.phtml?number=6" title="Читайте подробности">подробнее...</A></DIV>
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 style="text-align:left; font-size:8pt; ">
<b class=newsdate>Призыв-2003</b> - Какая армия нужна России?
<DIV ALIGN=RIGHT><A class=news HREF="reading/index.phtml?number=1" title="Читайте подробности">подробнее...</A></DIV>
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td colspan=3 style="text-align:left; font-size:8pt; ">
<b class=newsdate>Жизнь и кошелёк</b> - Сага о повышенной стипендии.
<br><i>Почему-то российские школяры возмутились, когда им прибавили стипендию аж на 25 процентов</i>
<DIV ALIGN=RIGHT><A class=news HREF="reading/index.phtml?number=2" title="Читайте подробности">подробнее...</A></DIV>
</td>
<td width=10></td>
</tr>

<tr bgcolor="#CBD5ED">
<td width=10></td>
<td width=10></td>
<td align="center">
<A class=menu HREF="http://fizmat.elsu.ru/reading/" title="Архив статей">··· Архив ···</A>
</td>
<td width=10></td>
<td width=10></td>
</tr>

</table>
</td>


<!-- Здесь заканчивается правая часть ****************************************************** -->

</tr>

<tr bgcolor="#B4BEE4">
<td colspan=3 height=20 align="center" valign="middle">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr valign="middle">
<td align="center" width="180"><a title="Сделать fizmat.elsu.ru стартовой страницей" class=menu href="" onClick="this.style.behavior='url(#default#homepage)';this.setHomePage('http://fizmat.elsu.ru/'); return false;">
Сделать страницу стартовой</a>
</td>
<td align="center" width="*">
<a title="Перейти вверх страницы" class=menu href="#top">
··· Вверх ···</a>
</td>
<td align="center" width="180"><a title="Добавить сайт fizmat.elsu.ru в избранное: Ctrl+D" class=menu href="" onClick="window.external.addFavorite
('http://fizmat.elsu.ru/', 'Физико-математический факультет ЕГУ им. И.А. Бунина - Главная страница'); return false;">
Добавить сайт в избранное</a>
</td>
</tr>
</table>
</td>
</tr>
<tr bgcolor="#304078" height=20>
<td colspan=3 align="center" valign="middle">
<font style="font-size: 7pt;" color="#FFFFFF">
<script language=JavaScript>
WriteModified()
</script>
Оптимизировано для Internet Explorer 5.5 и Shockwave Flash 5. Рекомендуемое разрешение экрана 800x600.
<a class=webmaster href="mailto:alexander.shataloff@gmail.com?subject=Письмо Web-мастеру fizmat.elsu.ru&Body=Уважаемый Web-мастер!" title="Напиши письмо Web-masterу">Web-master</a>
</font>
</td>
</tr>
</table>

<!-- Таблица высотой 5 пикселей -->

<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td align="center" valign="middle" height="5"> </td>
</tr>
</table>
</body>
</html>