<html>
<head>
  <title>Физико-математический факультет ЕГУ им. И.А. Бунина ->> Отдохни!</title>
  <meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
  <meta http-equiv="Content-Language" content="ru">
  <META content="Официальный сайт физико-математического факультета ЕГУ им. И.А. Бунина" name=Description>
  <META content="Елецкий Государственный Университет имени Ивана Алекеевича Бунина" name=Organisation>
  <META content="факультет университет высшее образование научная деятельность вуз школа студент абитуриент профессор доцент кандидат экзамен сессия зачет Елец Бунин ЕГУ аспирантура конференции наука" name=Keywords>
  <META content=alexander.shataloff@gmail.com name=OWNER>
  <META content="Шаталов Александр" name=Designer>
  <META content=index,follow name=ROBOTS>
  <META content="4 weeks" name=REVISIT-AFTER>
  <link href="http://fizmat.elsu.ru/images/logo.ico" rel="shortcut icon">
  <link href="http://fizmat.elsu.ru/styles/base.css" rel=stylesheet type=text/css>
  <script language=JavaScript src="http://fizmat.elsu.ru/scripts/others.js"></script>
</head>

<body ID=dbody NAME=dbody leftmargin="5" topmargin="5" marginwidth="5" marginheight="5" scroll=auto onload="Loading();">

<!--Таблица высотой 5 пикселей -->
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center" valign="middle" height="5"><A name=top></A></td>
  </tr>
</table>

<?php

 include("../../index/flash.html");

?>

<!-- Основная таблица -->
<table width="770" border="0" cellspacing="2" bgcolor="#304078" cellpadding="0" align="center" valign="middle">
  <tr>
    <td colspan=3 bgcolor="#B4BEE4" height=20 valign="middle">
      <table width="766" border="0" cellspacing="2" cellpadding="0">
	<tr>
	  <td width="230" align="left">
            <font style="font-size:8pt;"><I>
              &nbsp;
              <script language=JavaScript>
                WriteDate()
              </script>
            </I></font>
          </td>

          <td width="*">
            <table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#304078">
              <tr>
                <td width="10" align="center" bgcolor="#91A3D9">&nbsp;</td>
                <td width="10" align="center" bgcolor="#5E78C6">&nbsp;</td>
                <td width="10" align="center" bgcolor="#3C57A8">&nbsp;</td>
                <td width="*" align="center">
                  <font class=zagolovok>··· ОТДОХНИ! ···</font>
                </td>
                <td width="10" align="center" bgcolor="#3C57A8">&nbsp;</td>
                <td width="10" align="center" bgcolor="#5E78C6">&nbsp;</td>
                <td width="10" align="center" bgcolor="#91A3D9">&nbsp;</td>
              </tr>
            </table>
          </td>

          <td width="230" align="right">
            <font style="font-size:9pt;">
              <A class=menu href="javascript:history.back(1);" title="Назад">Назад</A>
              ·
              <A class=menu href="javascript:history.forward(1);" title="Вперед">Вперед</A>
              &nbsp;
            </font>
          </td>
        </tr>
      </table>
    </td>
  </tr>

  <tr>
    <td width="766" bgcolor="#DFE3F4" align="center" valign="middle" colspan=3>

    <table width="100%" height="100%" border="0" cellspacing="0" cellpadding="30"><tr><td align="center">

<!-- Здесь начинается содержание страницы ************************************************** -->

   <P class=textblock>
       Раздел находится в стадии развития. Пока он содержит только анекдоты.
   <BR>Наша копилка постоянно пополняется.
   <BR>Если у Вас есть интересные проекты, идеи или предложения,
   <BR>то обязательно присылайте их на
   <a class=text href="mailto:alexander.shataloff@gmail.com?subject=Письмо Web-мастеру fizmat.elsu.ru&Body=Уважаемый Web-мастер!">E-mail</a>
   <BR>Ждём Вашего участия!
   </P>

<?PHP

   // Чтение данных из файла и запись их в массив

   $q=10; //максимальное число выводимых записей
   $files = "funny.txt";
   $open = fopen($files, "r");
   $lines = file($files);
   fclose($open);
   $a = count($lines);

   if ($a>0) {

   print ("<hr width=\"100%\" align=\"center\" style=\"color: #304078;\" size=\"1\">");
   print ("<b style=\"font-size: 12pt;\">Количество анекдотов: $a</b>\n");
   print ("<hr width=\"100%\" align=\"center\" style=\"color: #304078;\" size=\"1\">");
   print ("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"10\">");

   if(!isset($number)) $number=0;

   if ($a>$q) { $u = $a - $q; } else { $u=0; $number=0;}

   $kol = $a/$q;
   $kol = ceil($kol);
   if ($kol-1<$number) {$number=0;}

   $u=$u-$q*$number;
   if ($u<0) {$u=0;}

   for ($i = $a-$q*$number-1; $i >= $u; $i--)
   {
     print ("<tr><td>");
     echo $lines[$i];
     print ("</td></tr>");

     if ($i!=$u)
     {
     print ("<tr><td><hr width=\"100%\" align=\"center\" style=\"color: #304078;\" size=\"1\">");
     print ("</td></tr>");
     }
   }

   print ("</table>\n");

   if ($a>$q) {
    print ("<p></p>");
    print ("<hr width=\"100%\" align=\"center\" style=\"color: #304078;\" size=\"1\">");

   for ($i=0; $i <= $kol-1; $i++)
    {
    $j=$i+1;
    if ($i!=$number) { print ("· <a href=\"http://fizmat.elsu.ru/rest/funny/index.phtml?number=$i\">$j</a> "); }
    else { print ("· <b>$j</b> "); }
    }

    print ("·");
   }

             }
   else
             {
   print ("<p style=\"font-size:12pt; text-align:center; line-height:18pt;\"><b>Раздел не содержит ни одного анекдота</b></p>");
             }

?>


<!-- Здесь заканчивается содержание страницы *********************************************** -->

      </td></tr></table>

    </td>
  </tr>

  <tr bgcolor="#B4BEE4">
    <td colspan=3 height=20 align="center" valign="middle">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr valign="middle">
          <td align="center" width="180"><a title="Сделать fizmat.elsu.ru стартовой страницей" class=menu href="" onClick="this.style.behavior='url(#default#homepage)';this.setHomePage('http://fizmat.elsu.ru/rest/index.html'); return false;">
          Сделать страницу стартовой</a>
          </td>
          <td align="center" width="*">
          <a title="Перейти вверх страницы" class=menu href="#top">
          ··· Вверх ···</a>
          </td>
          <td align="center" width="180"><a title="Добавить сайт fizmat.elsu.ru в избранное: Ctrl+D" class=menu href="" onClick="window.external.addFavorite
          ('http://fizmat.elsu.ru/rest/index.html', 'Физико-математический факультет ЕГУ им. И.А. Бунина - Отдохни!'); return false;">
          Добавить сайт в избранное</a>
          </td>
        </tr>
      </table>
     </td>
  </tr>

  <tr bgcolor="#304078" height=20>
    <td colspan=3 align="center" valign="middle">
      <font style="font-size: 7pt;" color="#FFFFFF">
        <script language=JavaScript>
          WriteModified()
        </script>
        Оптимизировано для Internet Explorer 5.5 и Shockwave Flash 5. Рекомендуемое разрешение экрана 800x600.
        <a class=webmaster href="mailto:alexander.shataloff@gmail.com?subject=Письмо Web-мастеру fizmat.elsu.ru&Body=Уважаемый Web-мастер!" title="Напиши письмо Web-masterу">Web-master</a>
      </font>
    </td>
  </tr>

</table>

<!--Таблица высотой 5 пикселей -->
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center" valign="middle" height="5"> </td>
  </tr>
</table>

<?php include("../../index/counters.html"); ?>

</body>
</html>